#!/bin/sh
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://cdn.jsdelivr.net/gh/junegunn/vim-plug@master/plug.vim

echo "installed vim-plug"

curl -fLo ~/.vimrc --create-dirs \
    https://cdn.jsdelivr.net/gh/ZGGSONG/vim@master/vimrc

echo "installed vimrc"

rm install
